apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: xkihb3xxt-java-quarkus 
  janus-idp.io/tekton: xkihb3xxt-java-quarkus
  backstage.io/kubernetes-id: xkihb3xxt-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: xkihb3xxt-java-quarkus
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml